
services:
    mosquitto-local:
        image: eclipse-mosquitto:latest
        container_name: mqtt-local
        expose:
            - "1883"
        networks:
            - mqtt-local-network
        volumes:
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/conf:/mosquitto/config

    postgres-local:
        image: postgres:latest
        container_name: postgres-local
        environment:
            - POSTGRES_DB=${POSTGRES_DB_LOCAL}
            - POSTGRES_USER=${POSTGRES_USER_LOCAL}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_LOCAL}
        volumes:
            - ./postgres/local/data:/var/lib/postgresql/data
        expose:
            - "5432"
        networks:
            - postgres-local-network

    manager-local:
        image: manager-local:latest
        container_name: manager-local
        build:
            context: ./manager
            dockerfile: Dockerfile
        expose:
            - 1883
        networks:
            - mqtt-local-network
            - postgres-local-network
        depends_on:
            - mosquitto-local
            - postgres-local


networks:
    mqtt-local-network:
        driver: bridge
    postgres-local-network:
        driver: bridge