
services:
    eclipse-mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mqtt-api
        ports:
            - "1883:1883"
        expose:
            - "1883"
        networks:
            - mqtt-api-network
        volumes:
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/conf:/mosquitto/config

    postgres-api:
        image: postgres:latest
        container_name: postgres-api
        environment:
            - POSTGRES_DB=${POSTGRES_DB_API}
            - POSTGRES_USER=${POSTGRES_USER_API}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API} #/run/secrets/postgres_password
        volumes:
            - ./postgres/api/data:/var/lib/postgresql/data
        expose:
            - "5432"
        networks:
            - postgres-api-network

    java-api:
        container_name: java-api
        build:
            context: ./api-service
            dockerfile: Dockerfile
        environment:
            - POSTGRES_URL=postgres-api:5432
            - POSTGRES_DATABASE=${POSTGRES_DB_API}
            - POSTGRES_USER=${POSTGRES_USER_API}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API}
        ports:
            - "8888:80"
        networks:
            - postgres-api-network
            - mqtt-api-network
        depends_on:
            - postgres-api
            - eclipse-mosquitto

    postgres-keycloak:
        image: postgres:latest
        container_name: postgres-keycloak
        environment:
            - POSTGRES_DB=${POSTGRES_DB_KEYCLOAK}
            - POSTGRES_USER=${POSTGRES_USER_KEYCLOAK}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_KEYCLOAK} #/run/secrets/postgres_password
        volumes:
            - ./postgres/keycloak/data:/var/lib/postgresql/data
        expose:
            - "5432"  # Expose to services inside the network
        networks:
            - keycloak-postgres-network  # Connect PostgreSQL to Keycloak
            - pgadmin-postgres-network   # Connect PostgreSQL to pgAdmin

    keycloak:
        image: keycloak/keycloak:latest
        container_name: keycloak
        environment:
            - KC_DB=${KC_DB}
            - KC_DB_URL_HOST=${KC_DB_URL_HOST}
            - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
            - KC_DB_USERNAME=${KC_DB_USERNAME}
            - KEYCLOAK_ADMIN=${KC_ADMIN}
            - KC_DB_PASSWORD=${KC_DB_PASSWORD} #/run/secrets/postgres_password
            - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD} #/run/secrets/keycloak_admin_password
        ports:
            - "8080:8080"
        networks:
            - keycloak-postgres-network  # Network between Keycloak and PostgreSQL
        depends_on:
            - postgres-keycloak
        command: start-dev

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5080:80"  # Expose pgAdmin on this port for external access
        networks:
            - postgres-api-network
            - pgadmin-postgres-network   # Connect PostgreSQL to pgAdmin
        depends_on:
            - postgres-api
            - postgres-keycloak


networks:
    mqtt-api-network:
        driver: bridge
    postgres-api-network:
        driver: bridge
    keycloak-postgres-network:
        driver: bridge  # Network for Keycloak and PostgreSQL
    pgadmin-postgres-network:
        driver: bridge  # Network for pgAdmin and PostgreSQL