
services:
    keycloak:
        image: keycloak/keycloak:latest
        container_name: keycloak
        environment:
            - KC_DB=${KC_DB}
            - KC_DB_URL_HOST=${KC_DB_URL_HOST}
            - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
            - KC_DB_USERNAME=${KC_DB_USERNAME}
            - KEYCLOAK_ADMIN=${KC_ADMIN}
            - KC_DB_PASSWORD=${KC_DB_PASSWORD} #/run/secrets/postgres_password
            - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD} #/run/secrets/keycloak_admin_password
        ports:
            - "8080:8080"
        networks:
            - keycloak-postgres-network  # Network between Keycloak and PostgreSQL
#        secrets:
#            - postgres_password
#            - keycloak_admin_password
        depends_on:
            - postgres
        command: start-dev

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} #/run/secrets/postgres_password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        expose:
            - "5432"  # Expose to services inside the network
        networks:
            - keycloak-postgres-network  # Connect PostgreSQL to Keycloak
            - pgadmin-postgres-network   # Connect PostgreSQL to pgAdmin
#        secrets:
#            - postgres_password

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"  # Expose pgAdmin on this port for external access
        networks:
            - pgadmin-postgres-network  # Network between pgAdmin and PostgreSQL
        depends_on:
            - postgres

networks:
    keycloak-postgres-network:
        driver: bridge  # Network for Keycloak and PostgreSQL
    pgadmin-postgres-network:
        driver: bridge  # Network for pgAdmin and PostgreSQL

volumes:
    postgres-data:

#secrets:
#    postgres_password:
#        file: secrets/postgres_password.txt
#    keycloak_admin_password:
#        file: secrets/keycloak_admin_password.txt
