[versions]

spark = "3.0"
junitBom = "5.9.1"

[libraries]

spark-core = {group = "org.zoomba-lang", name = "spark-core", version.ref = "spark"}
junit-jupiter = {group = "org.junit.jupiter", name = "junit-jupiter"}
junit-bom = {group = "org.junit", name = "junit-bom", version.ref = "junitBom"}